### PR TITLE
Update platform to alpha18

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/19)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 133 at r1](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19#-L5EG_nsLA6kn97eI_vA:-L5EG_nsLA6kn97eI_vB:bpxe8ie) ([raw file](https://github.com/vaadin/flow-spring-tutorial/blob/caa5bd3ca329ca98c8e93b5fae1dcf3d3a586587/pom.xml#L133)):*
> ```XML
>                                 </goals>
>                                 <configuration>
>                                     <frontendWorkingDirectory>${project.basedir}/src/main/resources/META-INF/resources/frontend/</frontendWorkingDirectory>
> ```

Not sure if this is the right path, check if it works in production mode.
If it does not, then change it the way it is in `spring-skeleton` please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 133 at r1](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19#-L5EG_nsLA6kn97eI_vA:-L5EJgoPzOCaJsA3_Rak:b-qlysp8) ([raw file](https://github.com/vaadin/flow-spring-tutorial/blob/caa5bd3ca329ca98c8e93b5fae1dcf3d3a586587/pom.xml#L133)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Not sure if this is the right path, check if it works in production mode.
If it does not, then change it the way it is in `spring-skeleton` please.
</blockquote></details>

`production` mode build succeeded. 

And I have checked the one we use in `spring-skeleton`, it is 
```
<configuration>
        <transpileOutputDirectory>${webapp.directory}</transpileOutputDirectory>
</configuration>
```
in this app, we are using `<frontendWorkingDirectory>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 133 at r1](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19#-L5EG_nsLA6kn97eI_vA:-L5EM7xMnyuPzlPVIUU0:blubknr) ([raw file](https://github.com/vaadin/flow-spring-tutorial/blob/caa5bd3ca329ca98c8e93b5fae1dcf3d3a586587/pom.xml#L133)):*
> in this app, we are using <frontendWorkingDirectory>.


Yeah, that's exactly what's interesting.
But if the actual application works, it's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pom.xml, line 133 at r1](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19#-L5EG_nsLA6kn97eI_vA:-L5EMbpZM7DyXr3eqrfH:bo491oo) ([raw file](https://github.com/vaadin/flow-spring-tutorial/blob/caa5bd3ca329ca98c8e93b5fae1dcf3d3a586587/pom.xml#L133)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> in this app, we are using <frontendWorkingDirectory>.


Yeah, that's exactly what's interesting.
But if the actual application works, it's fine.
</blockquote></details>

no, the application is not working  in productionMode, unfortunately.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-spring-tutorial/19)*

**Pull request merged**
