### PR TITLE
Update platform version to beta7

### PR DESCRIPTION
**Pull request by pekam**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-spring-tutorial/27)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pom.xml, line 145 at r1](https://beta.reviewable.io/reviews/vaadin/flow-spring-tutorial/27#-L9iWgqR6d95WPdyp_Gr:-L9iWgqR6d95WPdyp_Gs:bwkkg7m) ([raw file](https://github.com/vaadin/flow-spring-tutorial/blob/5507bd214e5e8f8fa96fade45387a90b78a09e59/pom.xml#L145)):*
> ```XML
>                         <groupId>com.vaadin</groupId>
>                         <artifactId>flow-maven-plugin</artifactId>
>                         <version>1.0.0.alpha21</version>
> ```

should not affect anything, but better to update this plugin also, beta 7? Beverage buddy is using beta 5 i think.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-spring-tutorial/27)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 145 at r1](https://beta.reviewable.io/reviews/vaadin/flow-spring-tutorial/27#-L9iWgqR6d95WPdyp_Gr:-L9iX0jODySZA2GRejob:b-2td7x7) ([raw file](https://github.com/vaadin/flow-spring-tutorial/blob/5507bd214e5e8f8fa96fade45387a90b78a09e59/pom.xml#L145)):*
> 7
crap.. beta6? version goes with flow

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-spring-tutorial/27)*

**Comment by pekam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 145 at r1](https://beta.reviewable.io/reviews/vaadin/flow-spring-tutorial/27#-L9iWgqR6d95WPdyp_Gr:-L9iYvo2BEPHfoySp7ee:b-896fix) ([raw file](https://github.com/vaadin/flow-spring-tutorial/blob/5507bd214e5e8f8fa96fade45387a90b78a09e59/pom.xml#L145)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> 7
crap.. beta6? version goes with flow
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-spring-tutorial/27)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-spring-tutorial/27#-:-L9iZHb3-k-FJQx8RW5V:bnfp4nl)*

**Pull request merged**
